name: HealthCheck
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      with:
        swift-version: "5.8.0"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
