name: ReleaseBuild
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v --configuration release

    - name: Upload binary
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: xcresultscrapper
        path: .build/arm64-apple-macosx/release/XCResultScrapperClient
